version: '3'
services:
  ####################################################################################################
  # The nginx Server
  ####################################################################################################
  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - applicationData:/var/www/html
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - wordpress
  ####################################################################################################
  # App
  ####################################################################################################
  wordpress:
    container_name: wordpress
    build:
      context: ./wordpress/
      dockerfile: Dockerfile
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=root
      - WORDPRESS_DB_NAME=wordpress
      - redis_php_ini_save_path="tcp://redis:6379"
    links:
      - mysql
      - redis
    volumes:
      - applicationData:/var/www/html
  ####################################################################################################
  # MySQL
  ####################################################################################################
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    expose:
      - 3306
    volumes:
      - mysqlData:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: wordpress
  ####################################################################################################
  # Redis
  ####################################################################################################
  redis:
    container_name: redis
    image: redis:5-stretch
    ports:
        - "6379:6379"
    expose:
        - 6379
    volumes:
        - redisData:/data
volumes:
  applicationData:
  mysqlData:
  redisData:
